#!/bin/bash
# Manage a planner file
#
# Copyright (C) 2013 Lal Thomas
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ACTION=$1

echo "invalid addon"

if [[ $ACTION == "usage" ]]; then
    echo "    invalidate"
    echo "      move invalid todo items (i.e todo items marked with tilde ~ sign) to invalid.txt"    
    exit
fi
shift

sed -i.bak -e '/./!d' "$TODO_FILE"

[ $TODOTXT_VERBOSE -gt 0 ] && grep "^~ " "$TODO_FILE"

grep "^~ " "$TODO_FILE" >> "$INVALID_FILE"
sed -i.bak '/^~ /d' "$TODO_FILE"

if [ $TODOTXT_VERBOSE -gt 0 ]; then
echo "TODO: $TODO_FILE invalid items archived."
fi
