#!/bin/bash
# todo.txt add-on to move the invalid todo items to invalid.txt file
# Copyright (c) Lal Thomas, http://lalamboori.blogspot.in
# License: GPL3, http://www.gnu.org/copyleft/gpl.html


ACTION=$1

if [[ $ACTION == "usage" ]]; then
    echo "    invalidate"
    echo "      move invalid todo items (i.e todo items marked with tilde ~ sign) to invalid.txt"    
    exit
fi
shift

sed -i.bak -e '/./!d' "$TODO_FILE"

[ $TODOTXT_VERBOSE -gt 0 ] && grep "^~ " "$TODO_FILE"

grep "^~ " "$TODO_FILE" >> "$INVALID_FILE"
sed -i.bak '/^~ /d' "$TODO_FILE"

if [ $TODOTXT_VERBOSE -gt 0 ]; then
echo "TODO: $TODO_FILE invalid items archived."
fi
